# Relaxed rules for Helm values and K8s manifests
extends: default
rules:
  line-length:
    max: 160
    allow-non-breakable-inline-mappings: true
  document-start: disable
  new-line-at-end-of-file: enable
  truthy: disable  # GitHub Actions uses "on:", workflow_dispatch: {} etc.

ignore:
  - .git/
