# argocd-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jfrog-platform
  namespace: argocd
spec:
  project: default
  sources:
    # Source 1: The Helm chart from JFrog
    - repoURL: https://charts.jfrog.io
      chart: jfrog-platform
      targetRevision: "11.4.2"
      helm:
        skipCrds: true
        valueFiles:
          - $values/customvalues.yaml
    # Source 2: Your Git repo with values
    - repoURL: https://github.com/nagarajuv-jfrog/jfrog-gitops-test.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: jfrog-platform
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: jfrog-platform-artifactory-nginx-certificate
      jsonPointers:
        - /data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true